### ISSUE TITLE
Check for root

### ISSUE THREAD

**Issue by MarijnDoeve** [uvapl/installer#4]
Bij WSL moeten we controleren of er niet ingelogd wordt als root. Dat komt wel eens voor als er iets mis gaat bij de eerste keer opstarten van WSL. Er wordt dan geen user aangemaakt. De oplossing in dat geval is Ubuntu resetten via de windows Settings.

https://askubuntu.com/a/1082091/967070

**Comment by stgm** [comment]
user_name=`whoami`

**Comment by stgm** [comment]
Fixed in 749694d.
